parameters:
- name: example
  type: string
  default: 'true'

trigger:
- master

pr:
- master

resources:
  repositories:
  - repository: infrastructure
    type: github
    endpoint: dave-yotta
    name: dave-yotta/yaml-master-repo
    ref: refs/heads/master

pool:
  vmImage: 'ubuntu-latest'

variables:
- template: api-vars.yaml@infrastructure

steps:
- template: hello-args.yaml@infrastructure
  parameters:
    name: build-san
    
#- template: yamls/call-script.yml@infrastructure

- ${{ if eq(variables['example'], 'true') }}:
  - script: echo "example was true"
    displayName: example was true

- ${{ if eq(variables['example'], 'false') }}:
  - script: echo "example was false"
    displayName: example was false

- script: |
    echo i shall be deployed! > build-file
    echo "1.0.0" >> build-file
  displayName: 'make a buildy file lol'

- script: |
    curl $(api.headers) -X PUT $(api.build.uri)/tags/Integrate
  displayName: Tag for integration
  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.Reason'], 'PullRequest')))

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: build-file
    artifact: build
    publishLocation: pipeline
