trigger:
- master

resources:
  repositories:
  - repository: infrastructure
    type: github
    endpoint: dave-yotta
    name: dave-yotta/yaml-master-repo
    tag: v1

pool:
  vmImage: 'ubuntu-latest'

steps:
- template: hello-args.yaml@infrastructure
  parameters:
    name: build-san

- script: |
    echo i shall be deployed! > build-file
    echo "1.0.0" >> build-file
  displayName: 'make a buildy file lol'

- script: |
    echo Build.BuildUri: $(Build.BuildUri)
    echo System.CollectionUri: $(System.CollectionUri)
    echo System.AccessToken: $(System.AccessToken)
    env
  displayName: testy

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: build-file
    artifact: build
    publishLocation: pipeline
