trigger:
- master

pr:
- master

resources:
  repositories:
  - repository: infrastructure
    type: github
    endpoint: dave-yotta
    name: dave-yotta/yaml-master-repo
    tag: v1

pool:
  vmImage: 'ubuntu-latest'

variables:
  apiHeaders: "-H \"Authorization: Bearer $(System.AccessToken)\" -H \"Content-Length: 0\""
  apiUri: "$(System.CollectionUri)$(System.TeamProject)/_apis/build/builds/$(Build.BuildId)"
steps:
- template: hello-args.yaml@infrastructure
  parameters:
    name: build-san

- script: |
    echo i shall be deployed! > build-file
    echo "1.0.0" >> build-file
  displayName: 'make a buildy file lol'

- script: |
    curl "$(apiHeaders)" -X PUT $(apiUri)/tags/Integrate
    curl "$(apiHeaders)" -X GET $(apiUri)/tags
  displayName: Tag for integration
  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.Reason'], 'PullRequest')))

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: build-file
    artifact: build
    publishLocation: pipeline
